name: CMake

on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'doc/**'

env:
  BUILD_TYPE: Release
  NDK_VER: 21.3.6528147
  NDK_ARCH: x86_64

jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMODERN_ARG_PARSER_TEST=1

    - name: Build and Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target run-test

  android:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: ${{env.NDK_ARCH}}
        target: google_apis
        ndk: ${{env.NDK_VER}}
        script: |
            mkdir -p ${{runner.workspace}}/build
            cd ${{runner.workspace}}/build
            cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DMODERN_ARG_PARSER_TEST=1 -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$ANDROID_SDK_ROOT/ndk/$NDK_VER/build/cmake/android.toolchain.cmake -DANDROID_ABI:STRING=$NDK_ARCH -DANDROID_PLATFORM:STRING=19 -DANDROID_STL:STRING=c++_static
            cmake --build . --config $BUILD_TYPE --target run-test

    
